language: python
python:
  - "2.7"
#   - "3.5"
cache: pip
install:
  - pip install .
#  - pip install -r requirements.txt
  - sudo bash -e install-binary.sh
script:
  - sudo apt-get install -y graphviz
  - bash -e make_output.sh
deploy:
  provider: script
  skip_cleanup: true
  keep_history: true
  script: >-
#     curl -L https://raw.githubusercontent.com/shouldsee/travis_test/master/make_encrypt_site.sh | bash -es . $HASH;
    bash make_encrypt_site.sh .
    curl -L https://raw.githubusercontent.com/shouldsee/travis_test/master/travis_push.sh | bash -es;
  on:
    branch: master    
env:
  global:
    HASH: a93194bed5709a448522d69b9a722c02d1e7e71f
#     GITHUB_PATH: "shouldsee/test_private"
    GITHUB_PATH: "shouldsee/polyq-figures"

# deploy:
#   provider: pages
#   github_token: $GITHUB_TOKEN
#   skip_cleanup: true
#   keep_history: true
#   target-branch: gh-pages
#   on:
#     branch: master
