language: python
python:
  - "2.7"
#  - "3.5"
cache: pip
install:
  - pip install .
#  - pip install -r requirements.txt
  - sudo bash -e install-binary.sh
script:
  - sudo apt-get install -y graphviz
  - bash -e make_output.sh
before_deploy:
  - bash -e make_encrypt_site.sh
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master
