language: python
python:
  - "2.7"
#  - "3.5"
cache: pip
install:
  - pip install .
#  - pip install -r requirements.txt
  - sudo bash -e install-binary.sh
script:
  - sudo apt-get install -y graphviz
  - bash -e make_output.sh
# before_deploy:

# deploy:
#   provider: pages
#   github_token: $GITHUB_TOKEN
#   skip_cleanup: true
#   keep_history: true
#   target-branch: gh-pages
#   on:
#     branch: master
deploy:
  provider: script
  skip_cleanup: true
  keep_history: true
  script: "bash -e make_encrypt_site.sh . $HASH; cd $HASH; find ..; bash -xe travis_push.sh"
  on:
    branch: master    
env:
  global:
    HASH: a93194bed5709a448522d69b9a722c02d1e7e71f
    GITHUB_PATH: "shouldsee/test_private"
